name: Build and Test C++ Application

on:
  push:
    branches:
      - "*"

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ build-essential clang-format

      - name: Format
        run: |
          sh ./scripts/format.sh

  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    needs: check_formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ build-essential 

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the application
        run: |
          cmake --build build --parallel

      - name: Run GoogleTest tests
        run: |
          cd build
          ctest --output-on-failure

  build_and_test_macos:
    runs-on: macos-latest
    needs: check_formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install cmake

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the application
        run: |
          cmake --build build --parallel

      - name: Run GoogleTest tests
        run: |
          cd build
          ctest --output-on-failure

  build_and_test_windows:
    runs-on: windows-latest
    needs: check_formatting

    steps:
#      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build the application
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build build --config Release

      - name: Run GoogleTest tests
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          cd build/Release
          ctest --output-on-failure

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pipeline
          path: build/Release/
